### PR TITLE
banner-carousel block redesign + section style classes removed

### PR DESCRIPTION
**Pull request by etomaello**
This PR contains the redesign of the banner-carousel block, which can be created as a two coulmns table where as a first element you need to put the image and as a second element the text.

sharepoint page:
https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B069DCEFA-C06B-49A4-8432-E8F64B6CF4A6%7D&file=tour-bernabeu.docx&action=default&mobileredirect=true

This PR contains also text harmonization to 15px and the removal of section's styling like "padding-bottom-small" or "main-section"

Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/sites/en/tour-bernabeu
- After: https://fix-banner-carousel-redesign--realmadrid--hlxsites.hlx.page/sites/en/tour-bernabeu

### CODE REVIEW

**Review by chicharr — CHANGES_REQUESTED** [review]
Please, Implement changes discussed on slack

**Comment by etomaello** [comment]
> Please, Implement changes discussed on slack

@chicharr this is done, shall I introduce createOptimizedPicture for banner-carousel block images?

**Comment by chicharr** [comment]
> > Please, Implement changes discussed on slack
> 
> @chicharr this is done, shall I introduce createOptimizedPicture for banner-carousel block images?

Yes, please

**Comment by etomaello** [comment]
> > > Please, Implement changes discussed on slack
> > 
> > 
> > @chicharr this is done, shall I introduce createOptimizedPicture for banner-carousel block images?
> 
> Yes, please

@chicharr done!

**Pull request merged**
