### PR TITLE
New smooth slider logic using JS new function instead of pure CSS

### PR DESCRIPTION
**Pull request by kacemait**
Modifying columns.js and columnsl.css and scripts.js. Creating new js function bindSwipeToElementWithForce in scripts.js that, in addition to bind the Swipe to an element, it calculates ‘swipeDistance’. This allows to handle swipe force without modifying your original bindSwipeToElement function, thus avoiding potential regressions.

I tried to handle the swipe force to calculate the distance and then use it to determine how many slides to scroll. I also tried to animate the scroll more smoothly by using the browser's built-in requestAnimationFrame function.
After testing mobile tabs swiping on a browser mobile emulator, I can feel that the swiping behaviour is not perfect as it can be expected when using the swiper.js library. 
I don't know if this can be due to differences in the way touch and mouse events are handled.
Additionally, it's possible that there are various other parameters and nuances that swiper.js takes into account to optimize the swiping functionality. These parameters, which may not have been fully replicated in my implementation, could significantly influence the overall user experience and efficiency of the swipe feature.

Fix[ #116 ](https://github.com/hlxsites/realmadrid/issues/116)

Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/tour/es/fragments/faq
- After: https://116-slider-tour-faq--realmadrid--hlxsites.hlx.page/tour/es/fragments/faq

### CODE REVIEW

**Comment by etomaello** [comment]
Hi @kacemait ,
I've tested the scroll from firefox browser's simulator and works pretty well, the problem is that on a real phone (e.g. iphone 12) the result is different:
if you swipe gently, the scroll works as expected while if you scroll normal or fast the behaviour is a bit odd, scrolls one tab at a time with a bit of lag.
I know that this is not part of the PR but the "+" icon to expand the answer is not centered in the bullet.
let's catch up via slack if you can't reproduce the behaviour.

**Comment by kacemait** [comment]
> Hi @kacemait , I've tested the scroll from firefox browser's simulator and works pretty well, the problem is that on a real phone (e.g. iphone 12) the result is different: if you swipe gently, the scroll works as expected while if you scroll normal or fast the behaviour is a bit odd, scrolls one tab at a time with a bit of lag. I know that this is not part of the PR but the "+" icon to expand the answer is not centered in the bullet. let's catch up via slack if you can't reproduce the behaviour.

Hi @etomaello, I've just commit a fix for the "+" to be centred on IOS Safari too. As discussed together on Slack, I also  commit some js code modification (bug fixing) to support questions that have answers composed of many paragraphs (because the English version content has a different structure than the tested Spanish version).

**Comment by etomaello** [comment]
Hi @kacemait faq style has been fixed correctly, there is just one open point to discuss with @chicharr about the scroll force from ios.

**Comment by etomaello** [comment]
Hi @chicharr ,
the carousels used for images do not have the scroll force handling.

**Comment by chicharr** [comment]
ok, we merge it as it is now. @kacemait  will check if the experience can be improved for IOs force swipe

**Pull request merged**
